version: '3'
services:
  db:
    container_name: api_db
    image: 'mysql:8.0'
    environment:
      - MYSQL_DATABASE=clientes_actividad13
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=password
      - DATABASE_HOST=db
    ports:
      - "3307:3306"
    volumes:
      - /data:/var/lib/mysql
    security_opt:
      - seccomp:unconfined

  api:
    build: ./Api
    restart: on-failure
    depends_on:
      - db
    links: 
      - db
    ports:
      - 8080:8080

  client:
    build: ./crud-clients
    restart: on-failure
    depends_on:
      - db
      - api
    links: 
      - db
      - api
    ports:
      - 3000:3000
    

